FROM tiangolo/uwsgi-nginx:python3.6

USER root
ADD nginx_setting/codewings.crt /etc/nginx/
ADD nginx_setting/codewings_private_dec_key.key /etc/nginx/

ENV UWSGI_INI nginx_setting/wsgiSetting.ini



RUN rm /etc/nginx/nginx.conf
ADD nginx_setting/nginx.conf /etc/nginx/nginx.conf



WORKDIR /etc/nginx


EXPOSE 80
EXPOSE 443

CMD service nginx start

